### ISSUE TITLE
WiFi setup on Pi3 

### ISSUE THREAD

**Issue by igniuss** [skarbat/pilove#1]
On the main webpage you've mentioned in the F.A.Q. how to setup WiFi

> Edit the file /etc/network/interfaces to set your ESSID / Passphrase pair, then sudo systemctl reboot.

This how-ever does not work, since the /etc/network/interfaces resets back to the original file on reboot.  Is there any other way to get this working? (or stop it from overwriting the changes)

**Comment by skarbat** [comment]
@igniuss sorry about that, it's oudated. Please edit the file `/boot/interfaces.txt` instead.
Due to `pipaos-tools` package - this allows to easily move your PI to a different wireless.

 * https://github.com/pipaos/pipaos-tools/blob/master/init/pipaos-init-network

**Comment by igniuss** [comment]
Sweet! Thanks a lot for the fast reply, got it working 👍
