### ISSUE TITLE
wifi on Pi Zero W

### ISSUE THREAD

**Issue by taxilly** [skarbat/pilove#3]
Using pilove 0.4
edited /boot/interfaces to correct essid, passphrase, edited wpa_supplicant.conf - still nothing...

Inspecting boot logs shows an error with dhcpcd,
![img_3312](https://user-images.githubusercontent.com/13081443/30249783-1358c1f4-963b-11e7-98c4-7c75badbc6d0.JPG)

I'm grateful for any help

**Comment by taxilly** [comment]
removing dhcpcd5 fixed dhcpcd service from failing since isc-dhcp-client is also installed.

upon further inspection the wlan0 interface isn't even present, only `lo` is, I suspect there are no drivers installed for the pi zero's wireless - searching for a driver install guide only results in people saying to install NOOBs, obviously not an option.

I know the wireless does works as I've tested it on Raspian Lite.

**Comment by skarbat** [comment]
This image is quite old... Did you try upgrading the kernel with `sudo rpi-update`?

**Comment by taxilly** [comment]
I can't exactly run that since there's no ethernet on the Pi Zero, I'll try downloading the [rpi/firmware](https://github.com/raspberrypi/firmware.git) files and moving them over to the Pi.

**Comment by taxilly** [comment]
Success; WiFi working, moved the SD onto a Pi3B, ran `rpi-update` over ethernet instead. Cheers.

**Comment by skarbat** [comment]
Nice! good to know!
